Release 2.2.0
nf-core/rnafusion pull request #320
Opened 2023-03-06 20:08 UTC by rannick

Release 2.2.0

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)
  - [x] If necessary, also make a PR on the nf-core/rnafusion _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-07 12:34 UTC, apeltzer approved these changes
Reviewed most of the PRs and also local tests on larger data are running fine now 👍🏻

2023-03-10 08:29 UTC, maxulysse commented
Amazing work

2023-03-13 08:27 UTC, apeltzer commented on CHANGELOG.md
> +## v2.2.0 - [2022/03/06]
```suggestion
## v2.2.0 - [2022/03/13]
```

2023-03-13 08:34 UTC, maxulysse requested changes

2023-03-13 08:37 UTC, apeltzer commented on README.md
> +[![AWS CI](https://img.shields.io/badge/CI%20tests-full%20size-FF9900?labelColor=000000&logo=Amazon%20AWS)](https://nf-co.re/rnafusion/results)[![Cite with Zenodo](http://img.shields.io/badge/DOI-10.
[![DOI](https://zenodo.org/badge/151721952.svg)](https://zenodo.org/badge/latestdoi/151721952)

Would be the right one

2023-03-13 12:17 UTC, rannick commented
I will need this one merged too for aws full tests: https://github.com/nf-core/rnafusion/pull/323

2023-03-13 12:29 UTC, rannick commented on conf/test_full.config
> -}
Yes! [cc85523](https://github.com/nf-core/rnafusion/pull/320/commits/cc85523bb37da771e72e39f2437db82de1a721e4)

2023-03-13 13:08 UTC, rannick commented on nextflow.config
>      genome                     = 'GRCh38'
Removed previous lines

2023-03-13 13:09 UTC, rannick commented on nextflow.config
> +    igenomes_ignore            = true
Removed

2023-03-13 13:09 UTC, rannick commented on nextflow.config
> +
Removed

2023-03-13 13:20 UTC, apeltzer approved these changes

2023-03-13 13:21 UTC, apeltzer commented
Merged that one for you, looks good now for me and everything that @maxulysse found was addressed now too 👍🏻

2023-03-13 13:54 UTC, maxulysse approved these changes

2023-03-13 16:30 UTC, merged