remove qualimap/rnaseq
nf-core/rnafusion pull request #407
Opened 2023-09-25 11:30 UTC by rannick

replace qualimap/rnaseq with mosdepth as mosdepth requires less cpu and memory

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, also make a PR on the nf-core/rnafusion _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2023-10-02 14:41 UTC, fevac commented
possibly best to just remove qualimap and not replace it with anything (picard already provides the gene body coverage information). Waiting to make a decision

2023-10-23 09:04 UTC, fevac requested changes
Nice! 🌟 I think it would be good to rename the PR to avoid future confusion. Then just minor comments about removing rrna bed since it doesn't seem to be used anymore

2023-10-23 09:04 UTC, fevac commented on nextflow_schema.json
> +                "rrna_intervals_bed": {
remove?

2023-10-23 09:04 UTC, fevac commented on subworkflows/local/qc_workflow.nf
> +        ch_rrna_intervals_bed
remove

2023-10-23 09:04 UTC, fevac commented on workflows/rnafusion.nf
> +ch_rrna_interval_bed = params.starfusion_build ?  Channel.fromPath(params.rrna_intervals_bed).map { it -> [[id:it.Name], it] }.collect() : Channel.fromPath("${params.ensembl_ref}/Homo_sapiens.GRCh38.
remove

2023-10-23 09:04 UTC, fevac commented on workflows/rnafusion.nf
> +        ch_rrna_interval_bed
remove?

2023-10-23 09:14 UTC, rannick commented
Changes addressed

2023-10-23 11:56 UTC, fevac approved these changes
🚀

2023-10-23 12:13 UTC, merged