from megafusion to vcf_collect
nf-core/rnafusion pull request #414
Opened 2023-09-29 15:31 UTC by rannick

Closes https://github.com/nf-core/rnafusion/issues/365 and https://github.com/nf-core/rnafusion/issues/356

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnafusion/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/rnafusion _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-11-08 13:46 UTC, peterpru approved these changes
Nice work 💯

2023-11-09 09:45 UTC, fevac requested changes
Nice!! 🌟

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def build_fusioninspector_dataframe(file):
Nice to add type hints for readability 
```suggestion
def build_fusioninspector_dataframe(file: str) -> pd.DataFrame:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def replace_value_with_column_name(row, value_to_replace, column_name):
```suggestion
def replace_value_with_column_name(row: pd.Series, value_to_replace: str, column_name: str) -> str:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def concatenate_columns(row):
```suggestion
def concatenate_columns(row: pd.Series) -> str:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def read_build_fusionreport(fusionreport_file):
```suggestion
def read_build_fusionreport(fusionreport_file: str) -> pd.DataFrame:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def column_manipulation(df):
```suggestion
def column_manipulation(df: pd.DataFrame) -> pd.DataFrame:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def write_vcf(df_to_print, header, out_file):
```suggestion
def write_vcf(df_to_print: pd.DataFrame, header: str, out_file: str) -> None:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def build_hgcn_dataframe(file):
```suggestion
def build_hgcn_dataframe(file: str) -> pd.DataFrame:
```

2023-11-09 09:45 UTC, fevac commented on bin/vcf_collect.py
> +def build_gtf_dataframe(file):
```suggestion
def build_gtf_dataframe(file: str) -> pd.DataFrame:
```

2023-11-13 15:40 UTC, fevac reviewed
added the issues I found here for simplicity

2023-11-13 15:40 UTC, fevac commented on bin/vcf_collect.py
> +##INFO=<ID=FRAME_STATUS,Number=.,Type=Float,Description="Frame status of the fusion">\n\
```suggestion
##INFO=<ID=FRAME_STATUS,Number=.,Type=String,Description="Frame status of the fusion">\n\
```

2023-11-13 15:40 UTC, fevac commented on bin/vcf_collect.py
> +##INFO=<ID=TRANSCRIPT_ID_A,Number=.,Type=Float,Description="Transcript id A ">\n\
```suggestion
##INFO=<ID=TRANSCRIPT_ID_A,Number=.,Type=String,Description="Transcript id A ">\n\
```

2023-11-13 15:40 UTC, fevac commented on bin/vcf_collect.py
> +##INFO=<ID=TRANSCRIPT_ID_B,Number=.,Type=Float,Description="Transcript id B">\n\
```suggestion
##INFO=<ID=TRANSCRIPT_ID_B,Number=.,Type=String,Description="Transcript id B">\n\
```

2023-11-13 15:40 UTC, fevac commented on bin/vcf_collect.py
> +            f"HGNC_ID_A={row['Left_hgnc_id']};HGNC_ID_B={row['Right_hgnc_id']};"
remove "HGNC:" prefix

2023-11-13 15:40 UTC, fevac commented on conf/modules.config
> +        ext.prefix = { "${meta.id}_fusion_data" }
exclude "_fusion_data" from sample ID in the vcf header

2023-11-13 15:40 UTC, fevac commented on bin/vcf_collect.py
> +        df.loc[index, "INFO"] = (
exclude quotes from being written in info field

2023-11-20 08:14 UTC, merged